const debug = false;

const alwaysUse = false;

// Grace period in minutes
const graceListTime = 2;

const adaptiveCard = {
    "card_title_isVisible": true,
    "card_title": "Title",
    "card_header": "https://i.ibb.co/6DWQg68/dxIwJT3.png",
    "card_description": "card description",
    "button1_title": "Button1",
    "button1_url": "https://someurl.com",
    "button2_title": "Button2",
    "button2_url": "https://someurl.com",
};

const priority_setup = [
    {
        "category": "category",
        "role": "headAdmin",
        "prio": 1,
    },
    {
        "category": "category",
        "role": "staff",
        "prio": 2,
    },
    {
        "category": "category",
        "role": "donator",
        "prio": 3,
    },
];

// TODO: Replace with autogenerated default?
const defaultPrio = 4;



/** !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !! DO NOT EDIT BELOW THIS LINE UNLESS YOU KNOW WHAT YOU'RE DOING !!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/

module.exports = {
    debug: getConBool("zqueue_debug", debug),
    alwaysUse: getConBool("zqueue_alwaysuse", alwaysUse),
    graceListTime: getConvarInt("zqueue_gracetime", graceListTime),
    adaptiveCard: adaptiveCard,
    priority_setup: priority_setup,
    defaultPrio: defaultPrio,
};

/** Returns convar or default value fixed to a true/false boolean
 * @param {boolean|string|number} con - Convar name
 * @param {boolean|string|number} def - Default fallback value
 * @returns {boolean} - parsed bool */
function getConBool(con, def) {
    if (typeof def == "boolean") def = def.toString();
    const ret = GetConvar(con, def);
    if (typeof ret == "boolean") return ret;
    if (typeof ret == "string") return ["true", "on", "yes", "y", "1"].includes(ret.toLocaleLowerCase().trim());
    if (typeof ret == "number") return ret > 0;
    return false;
}
